name: Sangkug Lym

external-image: false
picture: assets/images/profile.jpg

resume: true
resume-external: true
resume-url: https://drive.google.com/file/d/1CULApc_B5PO3Y-yyvglcBBEfrSOg9LtF/view?usp=sharing

url: https://erhoo82.github.io/

permalink: /:title/

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus
  categories: [blog, project]

# if you don't have any of social below, comment the line
facebook: sangkug.lym
googlescholar: citations?hl=en&user=bGc7lRMAAAAJ&authorid=2224392335791832711&view_op=list_works
linkedin: sangkug-lym-1827b566
email: sangkug.lym@gmail.com

width: normal

about: true
blog: true

read-time: true
show-tags: true
related: true

post-advance-links: [blog]

animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
